import { chromium } from 'playwright';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';

const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const errors=[];
const output=resolve('artifacts');
mkdirSync(output,{recursive:true});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
page.on('pageerror',e=>errors.push(e.message));
const url=pathToFileURL(resolve('docs/index.html')).href;
try {
  await page.goto(url,{waitUntil:'load'});
  await page.locator('#resource-grid .resource-card').first().waitFor();
  assert.equal(await page.locator('#resource-grid .resource-card').count(),12,'all curated resources rendered');
  assert.match(await page.locator('#spike-count').innerText(),/^\d+$/);
  const initialCount=Number(await page.locator('#spike-count').innerText());
  assert.ok(initialCount>0,'default neuron should emit spikes');
  await page.locator('#current').evaluate(el=>{el.value='0.50';el.dispatchEvent(new Event('input',{bubbles:true}));});
  const weakerCount=Number(await page.locator('#spike-count').innerText());
  assert.equal(weakerCount,0,'subthreshold step stimulus should emit no spikes');
  await page.locator('#reset-lab').click();
  assert.equal(Number(await page.locator('#spike-count').innerText()),initialCount,'reset restores baseline spike count');
  await page.locator('#threshold').evaluate(el=>{el.value='1.25';el.dispatchEvent(new Event('input',{bubbles:true}));});
  assert.ok(Number(await page.locator('#spike-count').innerText())<=initialCount,'higher threshold cannot increase spikes for this constant stimulus');
  await page.locator('#reset-lab').click();
  await page.locator('input[name="input-mode"][value="pulses"]').check({force:true});
  assert.equal(await page.locator('input[name="input-mode"][value="pulses"]').isChecked(),true,'pulse stimulus selectable');
  assert.match(await page.locator('#spike-count').innerText(),/^\d+$/,'pulse experiment returns spike count');
  await page.locator('#reset-lab').click();

  await page.locator('.filter-chip[data-filter="events"]').click();
  assert.equal(await page.locator('#resource-grid .resource-card').count(),3,'events category filter');
  await page.locator('#resource-search').fill('no-such-resource-1234');
  assert.equal(await page.locator('#resource-grid .resource-card').count(),0,'no matching resources');
  assert.equal(await page.locator('#resource-empty').isVisible(),true,'accessible empty state visible');
  await page.locator('#resource-search').fill('');
  await page.locator('.filter-chip[data-filter="all"]').click();
  assert.equal(await page.locator('#resource-grid .resource-card').count(),12,'all resources restored');
  await page.screenshot({path:resolve(output,'desktop.png'),fullPage:true});
  console.log('PASS desktop: navigation, LIF simulation, reset and resource filtering');
  await page.setViewportSize({width:390,height:844});
  await page.reload();
  await page.locator('#resource-grid .resource-card').first().waitFor();
  assert.equal(await page.locator('.menu-toggle').isVisible(),true,'mobile toggle visible');
  await page.locator('#menu-toggle').click();
  assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'),'true','menu expands');
  await page.locator('#site-menu a[href="#library"]').click();
  assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'),'false','menu closes on navigation');
  const overflow=await page.evaluate(()=>({viewport:window.innerWidth,scroll:document.documentElement.scrollWidth}));
  assert.ok(overflow.scroll<=overflow.viewport+1,'no mobile horizontal overflow: '+JSON.stringify(overflow));
  await page.setViewportSize({width:320,height:700});
  const narrow=await page.evaluate(()=>({viewport:window.innerWidth,scroll:document.documentElement.scrollWidth}));
  assert.ok(narrow.scroll<=narrow.viewport+1,'no 320px horizontal overflow: '+JSON.stringify(narrow));
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:resolve(output,'mobile.png'),fullPage:true});
  assert.deepEqual(errors,[],'no uncaught browser errors');
  console.log('PASS mobile: menu, in-page navigation, overflow and browser errors');
} finally {await browser.close();}
